dataset_dir: "./data"
source_folder: "cameras"
target_folder: "computers"
pretrained_model_name: "bert-base-uncased"
padding: "max_length"
max_seq_length: 256
batch_size: 32
learning_rate: 1e-5
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
mmd_lambda: 0.5
max_epochs: 5
accelerator: "gpu"
devices: 1
